# Generated by Django 4.1.4 on 2023-05-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='eventimages',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='event',
            name='eventimages',
            field=models.ImageField(default='', upload_to='event_images/'),
        ),
    ]
